name: flutter_stage
description: A widget that positions its children in a 3D scene. Zebiao Hu <zesage@gmail.com>
version: 0.0.1
homepage: https://github.com/zesage/flutter_stage

environment:
  sdk: '>=3.0.0-179.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: